# Generated by Django 5.0.1 on 2025-10-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('junior', 'Junior Developer'), ('senior', 'Senior Developer'), ('lead', 'Lead Developer'), ('admin', 'Admin')], default='junior', max_length=10, verbose_name='Rôle')),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
                'db_table': 'user_profile',
            },
        ),
    ]
