FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

EXPOSE 3000

# Lancer le serveur de développement
CMD ["npm", "start"]