services:
  db:
    image: mariadb:10.6
    container_name: sharetech_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - sharetech_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sharetech_backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_files:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - MEDIA_ROOT=${MEDIA_ROOT}
      - MEDIA_URL=${MEDIA_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sharetech_network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sharetech_frontend
    restart: always
    volumes:
      - ./frontend/src:/app/src          # Monter seulement src pour hot-reload
      - ./frontend/public:/app/public    # Monter public
      - /app/node_modules                # Volume anonyme pour node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true         # Pour hot-reload sur Windows
    depends_on:
      - backend
    networks:
      - sharetech_network
    stdin_open: true
    tty: true

volumes:
  mariadb_data:
    driver: local
  media_files:
    driver: local

networks:
  sharetech_network:
    driver: bridge