# Generated by Django 5.0.1 on 2025-10-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'assignation")),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to='notes.note', verbose_name='Note')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to='tags.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag de note',
                'verbose_name_plural': 'Tags de notes',
                'db_table': 'note_tag',
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['project'], name='idx_note_project'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['author'], name='idx_note_author'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status'], name='idx_note_status'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['project', 'status'], name='idx_note_project_status'),
        ),
        migrations.AddIndex(
            model_name='notetag',
            index=models.Index(fields=['note'], name='idx_note_tag_note'),
        ),
        migrations.AddIndex(
            model_name='notetag',
            index=models.Index(fields=['tag'], name='idx_note_tag_tag'),
        ),
        migrations.AddConstraint(
            model_name='notetag',
            constraint=models.UniqueConstraint(fields=('note', 'tag'), name='unique_note_tag'),
        ),
    ]
