# Generated by Django 5.2.6 on 2025-09-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='favorited_by',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#gray', max_length=7),
        ),
        migrations.DeleteModel(
            name='NoteFavorite',
        ),
    ]
